name: GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Deploy to GitHub Pages
      env:
        NODE_ENV: production
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/cty20010831/cty20010831.github.io.git
        npm run deploy
